apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: roboshop
  labels:
    component: app1
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app1
      project: roboshop
  template:
    metadata:
      labels:
        component: app1
        project: roboshop
    spec:
      containers:
      - name: app1
        image: shivanathbabu/app1:latest
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: roboshop
  labels:
    component: app1
    project: roboshop
spec:
  selector:
    component: app1
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app1-ingress-wildcard-host
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:139355608147:certificate/67316e00-9ae6-4e0e-b11c-68f472f644a8
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: ingress-test
spec:
  ingressClassName: alb
  rules:
  - host: "app1.teshome.online"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app1
            port:
              number: 80
 